In [3]:
import numpy as np
import pandas as pd

In [4]:
ser = pd.Series(np.random.random(5), name = "Column 01")

In [5]:
ser

0    0.754072
1    0.972496
2    0.724595
3    0.005246
4    0.243756
Name: Column 01, dtype: float64

In [6]:
ser[2]

0.7245953511613202

In [7]:
from pandas_datareader import data as wb

In [8]:
PG = wb.DataReader('PG', data_source='yahoo', start='2015-1-1')

In [9]:
PG

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2015-01-02,91.000000,89.919998,90.839996,90.440002,7251400.0,77.737968
2015-01-05,91.000000,89.849998,90.230003,90.010002,8626100.0,77.368362
2015-01-06,90.559998,89.260002,90.309998,89.599998,7791200.0,77.015945
2015-01-07,90.370003,89.559998,89.940002,90.070000,5986600.0,77.419930
2015-01-08,91.230003,90.129997,90.480003,91.099998,6823300.0,78.305275
2015-01-09,91.180000,90.120003,91.180000,90.250000,4872800.0,77.574654
2015-01-12,90.620003,89.510002,90.480003,89.919998,5250900.0,77.291000
2015-01-13,91.500000,89.769997,90.779999,90.300003,6727100.0,77.617653
2015-01-14,90.160004,89.430000,89.730003,89.989998,6418200.0,77.351166
2015-01-15,90.500000,89.339996,90.489998,89.860001,6768200.0,77.239433
2015-01-16,91.339996,89.870003,89.949997,91.250000,8815700.0,78.434212
2015-01-20,91.790001,90.500000,91.250000,91.190002,9869900.0,78.382645
2015-01-21,91.190002,89.629997,90.400002,90.730003,6974500.0,78.541924
2015-01-22,91.690002,89.870003,91.040001,91.620003,7211200.0,79.312355
2015-01-23,91.190002,89.949997,91.169998,90.080002,6745700.0,77.979248
2015-01-26,89.949997,88.739998,89.949997,89.580002,9371700.0,77.546402
2015-01-27,87.209999,86.019997,87.099998,86.489998,14417400.0,74.871513
2015-01-28,86.910004,85.010002,86.629997,85.150002,14033400.0,73.711502
2015-01-29,86.110001,85.150002,85.779999,85.669998,12054500.0,74.161652
2015-01-30,85.220001,84.250000,85.089996,84.290001,14685300.0,72.967041
2015-02-02,85.139999,83.680000,84.580002,85.120003,10278700.0,73.685532
2015-02-03,86.000000,85.120003,85.949997,85.949997,10747900.0,74.404037
2015-02-04,86.480003,85.550003,85.889999,85.790001,9212800.0,74.265541
2015-02-05,86.779999,86.099998,86.239998,86.699997,6531300.0,75.053284
2015-02-06,86.610001,85.150002,86.559998,85.610001,8429800.0,74.109703
2015-02-09,85.430000,84.589996,85.309998,85.050003,8811500.0,73.624947
2015-02-10,85.570000,84.820000,85.330002,85.389999,7059300.0,73.919266
2015-02-11,86.199997,85.150002,85.949997,85.639999,7184600.0,74.135681
2015-02-12,86.150002,85.410004,86.059998,86.029999,6074600.0,74.473282
2015-02-13,86.150002,85.500000,86.029999,85.900002,6272000.0,74.360771
...,...,...,...,...,...,...
2019-08-27,121.050003,119.779999,119.989998,120.550003,6996300.0,120.550003
2019-08-28,121.430000,119.629997,120.459999,121.400002,4600300.0,121.400002
2019-08-29,122.000000,120.320000,121.790001,121.180000,5011500.0,121.180000
2019-08-30,122.000000,119.510002,121.959999,120.230003,6007100.0,120.230003
2019-09-03,121.540001,119.629997,119.790001,121.360001,4959300.0,121.360001
2019-09-04,123.279999,121.459999,121.849998,123.209999,5586900.0,123.209999
2019-09-05,123.430000,122.180000,123.239998,122.760002,7491900.0,122.760002
2019-09-06,123.379997,122.540001,123.000000,122.870003,5306900.0,122.870003
2019-09-09,122.779999,121.779999,122.709999,122.169998,7662400.0,122.169998
2019-09-10,121.180000,119.580002,121.029999,119.879997,9582200.0,119.879997
2019-09-11,121.339996,119.360001,119.860001,121.269997,7565500.0,121.269997
2019-09-12,123.209999,121.620003,122.650002,122.769997,6194300.0,122.769997
2019-09-13,122.580002,121.500000,121.820000,122.120003,6777400.0,122.120003
2019-09-16,121.959999,119.019997,121.809998,119.750000,9626700.0,119.750000
2019-09-17,121.989998,119.440002,119.629997,121.160004,6377100.0,121.160004
2019-09-18,121.959999,120.769997,121.269997,121.410004,5684200.0,121.410004
2019-09-19,122.230003,121.239998,121.389999,121.900002,4525800.0,121.900002
2019-09-20,122.599998,121.750000,122.129997,122.239998,15362000.0,122.239998
2019-09-23,123.769997,121.970001,122.199997,123.220001,6060400.0,123.220001
2019-09-24,124.730003,123.360001,123.699997,123.610001,7633200.0,123.610001
2019-09-25,123.830002,122.949997,123.559998,123.019997,5812600.0,123.019997
2019-09-26,125.000000,123.529999,123.639999,124.309998,6984800.0,124.309998
2019-09-27,124.879997,123.720001,124.410004,124.570000,5589800.0,124.570000
2019-09-30,125.360001,124.129997,124.570000,124.379997,5206900.0,124.379997
2019-10-01,124.639999,123.199997,124.360001,123.849998,5415700.0,123.849998
2019-10-02,123.650002,120.209999,123.199997,121.080002,6755100.0,121.080002
2019-10-03,122.540001,120.839996,121.669998,121.739998,5171000.0,121.739998
2019-10-04,124.059998,121.989998,122.190002,124.000000,4377900.0,124.000000
2019-10-07,123.889999,122.680000,123.529999,122.839996,4749700.0,122.839996
2019-10-08,122.879997,121.080002,122.660004,122.027000,2560184.0,122.027000

In [10]:
PG.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1200 entries, 2015-01-02 to 2019-10-08
Data columns (total 6 columns):
High         1200 non-null float64
Low          1200 non-null float64
Open         1200 non-null float64
Close        1200 non-null float64
Volume       1200 non-null float64
Adj Close    1200 non-null float64
dtypes: float64(6)
memory usage: 65.6 KB

In [11]:
PG.head()

                 High        Low       Open      Close     Volume  Adj Close
Date
2015-01-02  91.000000  89.919998  90.839996  90.440002  7251400.0  77.737968
2015-01-05  91.000000  89.849998  90.230003  90.010002  8626100.0  77.368362
2015-01-06  90.559998  89.260002  90.309998  89.599998  7791200.0  77.015945
2015-01-07  90.370003  89.559998  89.940002  90.070000  5986600.0  77.419930
2015-01-08  91.230003  90.129997  90.480003  91.099998  6823300.0  78.305275

In [12]:
PG.tail()

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2019-10-02,123.650002,120.209999,123.199997,121.080002,6755100.0,121.080002
2019-10-03,122.540001,120.839996,121.669998,121.739998,5171000.0,121.739998
2019-10-04,124.059998,121.989998,122.190002,124.000000,4377900.0,124.000000
2019-10-07,123.889999,122.680000,123.529999,122.839996,4749700.0,122.839996
2019-10-08,122.879997,121.080002,122.660004,122.027000,2560184.0,122.027000

In [13]:
PG.head(20)

                 High        Low       Open      Close      Volume  Adj Close
Date
2015-01-02  91.000000  89.919998  90.839996  90.440002   7251400.0  77.737968
2015-01-05  91.000000  89.849998  90.230003  90.010002   8626100.0  77.368362
2015-01-06  90.559998  89.260002  90.309998  89.599998   7791200.0  77.015945
2015-01-07  90.370003  89.559998  89.940002  90.070000   5986600.0  77.419930
2015-01-08  91.230003  90.129997  90.480003  91.099998   6823300.0  78.305275
2015-01-09  91.180000  90.120003  91.180000  90.250000   4872800.0  77.574654
2015-01-12  90.620003  89.510002  90.480003  89.919998   5250900.0  77.291000
2015-01-13  91.500000  89.769997  90.779999  90.300003   6727100.0  77.617653
2015-01-14  90.160004  89.430000  89.730003  89.989998   6418200.0  77.351166
2015-01-15  90.500000  89.339996  90.489998  89.860001   6768200.0  77.239433
2015-01-16  91.339996  89.870003  89.949997  91.250000   8815700.0  78.434212
2015-01-20  91.790001  90.500000  91.250000  91.190002   9869900.0  78.382645
2015-01-21  91.190002  89.629997  90.400002  90.730003   6974500.0  78.541924
2015-01-22  91.690002  89.870003  91.040001  91.620003   7211200.0  79.312355
2015-01-23  91.190002  89.949997  91.169998  90.080002   6745700.0  77.979248
2015-01-26  89.949997  88.739998  89.949997  89.580002   9371700.0  77.546402
2015-01-27  87.209999  86.019997  87.099998  86.489998  14417400.0  74.871513
2015-01-28  86.910004  85.010002  86.629997  85.150002  14033400.0  73.711502
2015-01-29  86.110001  85.150002  85.779999  85.669998  12054500.0  74.161652
2015-01-30  85.220001  84.250000  85.089996  84.290001  14685300.0  72.967041

In [14]:
PG.tail(20)

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2019-09-11,121.339996,119.360001,119.860001,121.269997,7565500.0,121.269997
2019-09-12,123.209999,121.620003,122.650002,122.769997,6194300.0,122.769997
2019-09-13,122.580002,121.500000,121.820000,122.120003,6777400.0,122.120003
2019-09-16,121.959999,119.019997,121.809998,119.750000,9626700.0,119.750000
2019-09-17,121.989998,119.440002,119.629997,121.160004,6377100.0,121.160004
2019-09-18,121.959999,120.769997,121.269997,121.410004,5684200.0,121.410004
2019-09-19,122.230003,121.239998,121.389999,121.900002,4525800.0,121.900002
2019-09-20,122.599998,121.750000,122.129997,122.239998,15362000.0,122.239998
2019-09-23,123.769997,121.970001,122.199997,123.220001,6060400.0,123.220001
2019-09-24,124.730003,123.360001,123.699997,123.610001,7633200.0,123.610001
2019-09-25,123.830002,122.949997,123.559998,123.019997,5812600.0,123.019997
2019-09-26,125.000000,123.529999,123.639999,124.309998,6984800.0,124.309998
2019-09-27,124.879997,123.720001,124.410004,124.570000,5589800.0,124.570000
2019-09-30,125.360001,124.129997,124.570000,124.379997,5206900.0,124.379997
2019-10-01,124.639999,123.199997,124.360001,123.849998,5415700.0,123.849998
2019-10-02,123.650002,120.209999,123.199997,121.080002,6755100.0,121.080002
2019-10-03,122.540001,120.839996,121.669998,121.739998,5171000.0,121.739998
2019-10-04,124.059998,121.989998,122.190002,124.000000,4377900.0,124.000000
2019-10-07,123.889999,122.680000,123.529999,122.839996,4749700.0,122.839996
2019-10-08,122.879997,121.080002,122.660004,122.027000,2560184.0,122.027000

In [18]:
tickers = ['PG', 'MSFT', 'T', 'F', 'GE']
new_data = pd.DataFrame()
for t in tickers:
    new_data[t] = wb.DataReader(t, data_source='yahoo', start='2015-1-1')['close']

KeyError: 'close'

In [16]:
new_data.tail()

Empty DataFrame
Columns: []
Index: []

In [17]:
new_data.head()

Empty DataFrame
Columns: []
Index: []